### ISSUE TITLE
potential typo in bindings

### ISSUE THREAD

**Issue by joprice** [Khady/ocaml-argon2#8]
I was having trouble with static linking of this library, due to the symbols not being found at runtime, so I tried switching it over to use stub generation https://github.com/Khady/ocaml-argon2/compare/master...joprice:stubs. This got it to work, but while doing so, I noticed that `argon2id_verify` calls `argon2d_verify`  https://github.com/Khady/ocaml-argon2/blob/master/src/argon2.ml#L227.

```ocaml
let argon2id_verify = verify "argon2d_verify"
```

**Comment by Khady** [comment]
thanks!
